### ISSUE TITLE
why miss so many circRNA to putout ?

### ISSUE THREAD

**Issue by gnilihzeux** [bioinfo-biols/CIRIquant#18]
Dear author,
  I had input a bed containing **135** circRNAs from DCC, but got only **8** in final gtf, *which were all in `Chr1`*. 
  In addition, there were **127** circRNAs in `{sample_nm}`_index.fa but only **47** in `{sample_nm}`_denovo.sorted.bam.

So, why there were so many gaps?

Thanks a lot.

**Comment by Kevinzjy** [comment]
That's weird, could you try running CIRIquant without --bed option, which will use embedded version of CIRI2 for circRNA prediction?

**Comment by gnilihzeux** [comment]
OK, I'll try & return later.

**Comment by gnilihzeux** [comment]
Hi, I got a same results with '--tool & --circ'.

My comands are list below.

By the way, '--circ' should be a **bed-4 format** but not mentioned in the manual, which you should have a update.

## my config
```
name: hg19
tools:
  bwa: /root/miniconda2/bin/bwa
  hisat2: /root/miniconda2/bin/hisat2
  stringtie: /root/miniconda2/bin/stringtie
  samtools: /root/miniconda2/bin/samtools
  
reference:
  fasta: /root/Database/ref_genome/hg19/gencode_grch37p13.fa
  gtf: /root/Database/ref_genome/hg19/gencode_grch37p13.gtf
  bwa_index: /root/Database/ref_genome/hg19/bwa_index/gencode_grch37p13.fa
  hisat_index: /root/Database/ref_genome/hg19/hisat2_index/gencode_grch37p13
```
## 1st run
```
docker run -v /root:/root --name ciriq_${sm_nm} ciriquant:v1.1 \
  /root/miniconda2/bin/CIRIquant \
            -t 8 \
            -1 ${TRIM_DIR}/${sm_nm}_trim_R1.fq.gz \
            -2 ${TRIM_DIR}/${sm_nm}_trim_R2.fq.gz \
            --config ${PRJ_DIR}/ciriquant.hg19.yml \
            -o ${CIRIQ_DIR} \
            -p ${sm_nm} \
            -l 2 \
            --bed ${CIRIQ_DIR}/circ.bed \
            --log ${CIRIQ_DIR}/${sm_nm}.log
```

## 2nd run

```
docker run -v /root:/root --name ciriq_${sm_nm} ciriquant:v1.1 \
  /root/miniconda2/bin/CIRIquant \
            -t 16 \
            -1 ${TRIM_DIR}/${sm_nm}_trim_R1.fq.gz \
            -2 ${TRIM_DIR}/${sm_nm}_trim_R2.fq.gz \
            --config ${PRJ_DIR}/ciriquant.hg19.yml \
            -o ${CIRIQ_DIR} \
            -p ${sm_nm} \
            -l 2 \
            --circ ${CIRIQ_DIR}/circ.bed \
            --tool DCC \
            --bam ${CIRIQ_DIR}/align/${sm_nm}.sorted.bam \
            --log ${CIRIQ_DIR}/${sm_nm}.log
```
